import { TableSchema } from "./types";

export const orderUpsertSql = `
  INSERT INTO orders (
    id,
    status,
    deliveryMethod,
    amount,
    tax,
    serviceCharge,
    cashCollected,
    changeGiven,
    total,
    deliveryFee,
    specialInstructions,
    recipientName,
    occasion,
    initiator,
    recipientPhone,
    scheduledAt,
    address,
    reference,
    externalReference,
    orderMode,
    orderChannel,
    orderType,
    confirmedBy,
    confirmedAt,
    cancelledBy,
    cancelledAt,
    cancellationReason,
    createdAt,
    updatedAt,
    timeline,
    customerId,
    outletId,
    cartId,
    paymentReference,
    paymentMethod,
    paymentStatus,
    discount,
    markup,
    deletedAt,
    recordId,
    version
  ) VALUES (
    @id,
    @status,
    @deliveryMethod,
    @amount,
    @tax,
    @serviceCharge,
    @cashCollected,
    @changeGiven,
    @total,
    @deliveryFee,
    @specialInstructions,
    @recipientName,
    @occasion,
    @initiator,
    @recipientPhone,
    @scheduledAt,
    @address,
    @reference,
    @externalReference,
    @orderMode,
    @orderChannel,
    @orderType,
    @confirmedBy,
    @confirmedAt,
    @cancelledBy,
    @cancelledAt,
    @cancellationReason,
    @createdAt,
    @updatedAt,
    @timeline,
    @customerId,
    @outletId,
    @cartId,
    @paymentReference,
    @paymentMethod,
    @paymentStatus,
    @discount,
    @markup,
    @deletedAt,
    @recordId,
    @version
  )
  ON CONFLICT(id) DO UPDATE SET
    status = excluded.status,
    deliveryMethod = excluded.deliveryMethod,
    amount = excluded.amount,
    tax = excluded.tax,
    serviceCharge = excluded.serviceCharge,
    cashCollected = excluded.cashCollected,
    changeGiven = excluded.changeGiven,
    total = excluded.total,
    deliveryFee = excluded.deliveryFee,
    specialInstructions = excluded.specialInstructions,
    recipientName = excluded.recipientName,
    occasion = excluded.occasion,
    initiator = excluded.initiator,
    recipientPhone = excluded.recipientPhone,
    scheduledAt = excluded.scheduledAt,
    address = excluded.address,
    reference = excluded.reference,
    externalReference = excluded.externalReference,
    orderMode = excluded.orderMode,
    orderChannel = excluded.orderChannel,
    orderType = excluded.orderType,
    confirmedBy = excluded.confirmedBy,
    confirmedAt = excluded.confirmedAt,
    cancelledBy = excluded.cancelledBy,
    cancelledAt = excluded.cancelledAt,
    cancellationReason = excluded.cancellationReason,
    updatedAt = excluded.updatedAt,
    timeline = excluded.timeline,
    customerId = excluded.customerId,
    outletId = excluded.outletId,
    cartId = excluded.cartId,
    paymentReference = excluded.paymentReference,
    paymentMethod = excluded.paymentMethod,
    paymentStatus = excluded.paymentStatus,
    discount = excluded.discount,
    markup = excluded.markup,
    deletedAt = excluded.deletedAt,
    recordId = excluded.recordId,
    version = excluded.version
  WHERE excluded.version >= orders.version OR excluded.updatedAt >= orders.updatedAt OR orders.updatedAt IS NULL OR orders.cartId IS NULL
`;

export const buildOrderUpsertParams = (o: any) => ({
  id: o.id,
  status: o.status,
  deliveryMethod: o.deliveryMethod,
  amount: o.amount,
  tax: o.tax,
  serviceCharge: o.serviceCharge,
  cashCollected: o.cashCollected,
  changeGiven: o.changeGiven,
  total: o.total,
  deliveryFee: o.deliveryFee,
  specialInstructions: o.specialInstructions,
  recipientName: o.recipientName,
  occasion: o.occasion,
  initiator: o.initiator,
  recipientPhone: o.recipientPhone,
  scheduledAt: o.scheduledAt,
  address: o.address,
  reference: o.reference,
  externalReference: o.externalReference,
  orderMode: o.orderMode,
  orderChannel: o.orderChannel,
  orderType: o.orderType,
  confirmedBy: o.confirmedBy,
  confirmedAt: o.confirmedAt,
  cancelledBy: o.cancelledBy,
  cancelledAt: o.cancelledAt,
  cancellationReason: o.cancellationReason,
  createdAt: o.createdAt,
  updatedAt: o.updatedAt,
  timeline: Array.isArray(o.timeline) ? JSON.stringify(o.timeline) : o.timeline,
  customerId: o.customerId,
  outletId: o.outletId,
  cartId: o.cartId,
  paymentReference: o.paymentReference,
  paymentMethod: o.paymentMethod,
  paymentStatus: o.paymentStatus,
  discount: o.discount,
  markup: o.markup,
  deletedAt: o.deletedAt,
  recordId: o.recordId,
  version: o.version,
});

export const orderSchema: TableSchema = {
  name: "orders",
  create: `
    CREATE TABLE IF NOT EXISTS orders (
      id TEXT PRIMARY KEY,
      status TEXT,
      deliveryMethod TEXT,
      amount REAL,
      tax REAL,
      serviceCharge REAL,
      cashCollected REAL,
      changeGiven REAL,
      total REAL,
      deliveryFee REAL,
      specialInstructions TEXT,
      recipientName TEXT,
      occasion TEXT,
      initiator TEXT,
      recipientPhone TEXT,
      scheduledAt TEXT,
      address TEXT,
      reference TEXT,
      externalReference TEXT,
      orderMode TEXT,
      orderChannel TEXT,
      orderType TEXT,
      confirmedBy TEXT,
      confirmedAt TEXT,
      cancelledBy TEXT,
      cancelledAt TEXT,
      cancellationReason TEXT,
      createdAt TEXT,
      updatedAt TEXT,
      timeline TEXT,
      customerId TEXT,
      outletId TEXT,
      cartId TEXT,
      paymentReference TEXT,
      paymentMethod TEXT,
      paymentStatus TEXT,
      discount REAL,
      markup REAL,
      deletedAt TEXT,
      recordId TEXT,
      version INTEGER DEFAULT 0
    );
  `,
  indexes: [
    "CREATE INDEX IF NOT EXISTS idx_orders_outletId ON orders(outletId)",
    "CREATE INDEX IF NOT EXISTS idx_orders_customerId ON orders(customerId)",
    "CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status)",
    "CREATE INDEX IF NOT EXISTS idx_orders_orderMode ON orders(orderMode)",
  ],
};
