import { TableSchema } from "./types";

export const productionV2UpsertSql = `
  INSERT INTO productions_v2 (
    id,
    status,
    previousStatus,
    workflowPath,
    recipeValidationStatus,
    recipeValidationStrategy,
    initiator,
    inventoryCheckedBy,
    inventoryApprovedBy,
    productionStartedBy,
    qcApprovedBy,
    inventoryCheckedAt,
    inventoryApprovedAt,
    preparationStartedAt,
    qcStartedAt,
    readyAt,
    cancelReason,
    metadata,
    createdAt,
    updatedAt,
    outletId,
    batchId,
    productionDate,
    productionTime,
    productionDueDate,
    recordId,
    version
  ) VALUES (
    @id,
    @status,
    @previousStatus,
    @workflowPath,
    @recipeValidationStatus,
    @recipeValidationStrategy,
    @initiator,
    @inventoryCheckedBy,
    @inventoryApprovedBy,
    @productionStartedBy,
    @qcApprovedBy,
    @inventoryCheckedAt,
    @inventoryApprovedAt,
    @preparationStartedAt,
    @qcStartedAt,
    @readyAt,
    @cancelReason,
    @metadata,
    @createdAt,
    @updatedAt,
    @outletId,
    @batchId,
    @productionDate,
    @productionTime,
    @productionDueDate,
    @recordId,
    @version
  )
  ON CONFLICT(id) DO UPDATE SET
    status = excluded.status,
    previousStatus = excluded.previousStatus,
    workflowPath = excluded.workflowPath,
    recipeValidationStatus = excluded.recipeValidationStatus,
    recipeValidationStrategy = excluded.recipeValidationStrategy,
    initiator = excluded.initiator,
    inventoryCheckedBy = excluded.inventoryCheckedBy,
    inventoryApprovedBy = excluded.inventoryApprovedBy,
    productionStartedBy = excluded.productionStartedBy,
    qcApprovedBy = excluded.qcApprovedBy,
    inventoryCheckedAt = excluded.inventoryCheckedAt,
    inventoryApprovedAt = excluded.inventoryApprovedAt,
    preparationStartedAt = excluded.preparationStartedAt,
    qcStartedAt = excluded.qcStartedAt,
    readyAt = excluded.readyAt,
    cancelReason = excluded.cancelReason,
    metadata = excluded.metadata,
    updatedAt = excluded.updatedAt,
    outletId = excluded.outletId,
    batchId = excluded.batchId,
    productionDate = excluded.productionDate,
    productionTime = excluded.productionTime,
    productionDueDate = excluded.productionDueDate,
    recordId = excluded.recordId,
    version = excluded.version
  WHERE excluded.version >= productions_v2.version OR excluded.updatedAt >= productions_v2.updatedAt OR productions_v2.updatedAt IS NULL
`;

export const buildProductionV2UpsertParams = (p: any) => ({
  id: p.id,
  status: p.status,
  previousStatus: p.previousStatus,
  workflowPath: p.workflowPath,
  recipeValidationStatus: p.recipeValidationStatus,
  recipeValidationStrategy: p.recipeValidationStrategy,
  initiator: p.initiator,
  inventoryCheckedBy: p.inventoryCheckedBy,
  inventoryApprovedBy: p.inventoryApprovedBy,
  productionStartedBy: p.productionStartedBy,
  qcApprovedBy: p.qcApprovedBy,
  inventoryCheckedAt: p.inventoryCheckedAt,
  inventoryApprovedAt: p.inventoryApprovedAt,
  preparationStartedAt: p.preparationStartedAt,
  qcStartedAt: p.qcStartedAt,
  readyAt: p.readyAt,
  cancelReason: p.cancelReason,
  metadata: p.metadata && typeof p.metadata === "object" ? JSON.stringify(p.metadata) : p.metadata,
  createdAt: p.createdAt,
  updatedAt: p.updatedAt,
  outletId: p.outletId,
  batchId: p.batchId,
  productionDate: p.productionDate,
  productionTime: p.productionTime,
  productionDueDate: p.productionDueDate,
  recordId: p.recordId,
  version: Number(p.version || 0),
});

export const productionV2Schema: TableSchema = {
  name: "productions_v2",
  create: `
    CREATE TABLE IF NOT EXISTS productions_v2 (
      id TEXT PRIMARY KEY,
      status TEXT,
      previousStatus TEXT,
      workflowPath TEXT,
      recipeValidationStatus TEXT,
      recipeValidationStrategy TEXT,
      initiator TEXT,
      inventoryCheckedBy TEXT,
      inventoryApprovedBy TEXT,
      productionStartedBy TEXT,
      qcApprovedBy TEXT,
      inventoryCheckedAt TEXT,
      inventoryApprovedAt TEXT,
      preparationStartedAt TEXT,
      qcStartedAt TEXT,
      readyAt TEXT,
      cancelReason TEXT,
      metadata TEXT,
      createdAt TEXT,
      updatedAt TEXT,
      outletId TEXT,
      batchId TEXT,
      productionDate TEXT,
      productionTime TEXT,
      productionDueDate TEXT,
      recordId TEXT,
      version INTEGER DEFAULT 0 NOT NULL
    );
  `,
  indexes: [
    "CREATE INDEX IF NOT EXISTS idx_productions_v2_outletId ON productions_v2(outletId)",
    "CREATE INDEX IF NOT EXISTS idx_productions_v2_status ON productions_v2(status)",
  ],
};
